replicaCount: 3

image:
  repository: us.gcr.io/rlt-demo/rlt-demo-app
  tag: latest
  pullPolicy: Always

ports:
  containerPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/whitelist-source-range: 127.0.0.1
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - rlt-demo.exitprompt.com
  tls: []

fullnameOverride: rlt-demo

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
