replicaCount: 3

image:
  repository: us.gcr.io/rlt-demo/rlt-demo-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - rlt-demo.exitprompt.com
  tls: []


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
